import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import '../styles/fonts/Fonts/WEB/css/nippo.css';
import Head from 'next/head';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <head>
        <title>GeneX - Make Your Design Better</title>
        <link rel="icon" href="/favicon.ico" />

        <meta content="GeneX - Make Your Design Better" property="og:title" />
        <meta content="website" property="og:type" />
        <meta
          content="We are an independent creative studio helping startups, scale-ups and enterprise companies build world-class brands."
          property="og:description"
        />
        <meta content="/background.png" property="og:image" />
      </head>
      <body className="h-full">{children}</body>
    </html>
  );
}
