import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import '../styles/fonts/Fonts/WEB/css/nippo.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <head>
        <title>GeneX - Make Your Design Better</title>
        <meta
          property="og:title"
          content="GeneX - Make Your Design Better"
        ></meta>
        <link rel="icon" href="./favicon.ico" sizes="any" />
        <link rel="icon" href="/favicon.ico" sizes="any" />

        <meta
          name="description"
          content="We are an independent creative studio helping startups, scale-ups and enterprise companies build world-class brands."
        ></meta>
        <meta
          name="og:description"
          content="We are an independent creative studio helping startups, scale-ups and enterprise companies build world-class brands."
        ></meta>
        <meta property="og:image" content="./background.png" />
      </head>
      <body className="h-full">{children}</body>
    </html>
  );
}
